### PR TITLE
Merge gfx-rs backend resize fix from elrnv/gfx-update to veloren/conrod

### PR DESCRIPTION
**Pull request by ghost**
Needed for [#12](https://github.com/veloren/game/issues/12)

### CODE REVIEW

**Comment by zesterer** [comment]
@treenix CI failed. Any chance we could work out why?

**Comment by ghost** [comment]
@zesterer seems to be rustdoc that fails

**Comment by zesterer** [comment]
@treenix Reckon you can fix it before we merge?

**Comment by ghost** [comment]
@zesterer `cargo test --features "winit glium" --verbose` is the command that fails. If I run it on my machine it works fine. Seems to be an issue with travis. And since we are not using glium it should be fine

**Pull request merged**
